#!/bin/sh

# Print help
if [ "$1" = "--help" ]; then
	echo "Usage: $0 [context] [...args]"
	echo "  context syntax: [first] | [first]-[second]"
	exit 0
fi

if [ $# -gt 0 ]; then
	# Get context from first parameter and shift
	CONTEXT="$1"
	shift
else
	CONTEXT=""
fi

# If context is empty, set to the default context
if [ -z $CONTEXT ]; then
	CONTEXT="dev"
fi

# If arguments are empty, set to the default arguments
if [ -z $@ ]; then
	ARGS="up -d"
else
	ARGS=$@
fi

# Set compose file arguments
if [ -f "docker-compose.$CONTEXT.yml" ]; then
	COMPOSE_FILE_ARGS=" -f docker-compose.yml -f docker-compose.$CONTEXT.yml"

elif [ $CONTEXT = "prod" ]; then
	COMPOSE_FILE_ARGS=" -f docker-compose.yml"

elif [ $CONTEXT = "dev" ]; then
	COMPOSE_FILE_ARGS="" # Use default docker compose behavior

elif [ $CONTEXT = "notebooks" ]; then
	COMPOSE_FILE_ARGS=" -f docker-compose-notebooks.yml"

elif [ $CONTEXT = "notebooks-gpu" ]; then
	COMPOSE_FILE_ARGS=" -f docker-compose-notebooks.yml -f docker-compose-notebooks.gpu.yml"

else # Error
	echo "Error: Unknown context '$CONTEXT'"
	exit 1
fi

# Run docker compose
echo ""
echo "> docker compose$COMPOSE_FILE_ARGS $ARGS"
echo ""
exec docker compose$COMPOSE_FILE_ARGS $ARGS
